export const SET_GAME_FIELD_OPTIONS = "SET_GAME_FIELD";
export const CHOICE_CELL = "CHOICE_CELL";
export const GENERATE_RANDOM_FIELD = "GENERATE_RANDOM_FIELD";
export const SET_GAME_STARTED = "SET_GAME_STARTED";
export const START_GAME = "START_GAME";
export const STOP_GAME = "STOP_GAME";
